### PR TITLE
update project with latest setuptools best practices

### PR DESCRIPTION
**Pull request by 4383**
Hey!

### Overview
Introduce best practices for setuptools latest version. Using `setup.cfg` instead of `setup.py` to define packaging configuration.

### Changes
- Move config to `setup.cfg`
- Update documentation for using this feature

### CODE REVIEW

**Comment by guyskk** [comment]
What's the advantages and disadvantages of `Using setup.cfg instead of setup.py`? Is there any refers to setuptools best practices? 

PS: The CI failed because a known issue, just ignore it.

**Comment by 4383** [comment]
This approach allows automation scenarios but also reduces boilerplate code in some cases. [cf. documentation](http://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files)

The benefits of this approach are multiples:
- centralize configuration (packaging (wheel, setuptools), tests, linting, pypi config, distutils, etc...)
- reduce python code complexity
- simplify python code review
- automatizing project generation (automatizing git tag generate with the same version, etc...)
- provide a beutiful semver management
- manage properly requirements by platform (dev, test, production)

Example of semver management:
```python
import pkg_resources
from os import path
from setuptools.config import read_configuration


def _extract_version(package_name):
    try:
        return pkg_resources.get_distribution(package_name).version
    except pkg_resources.DistributionNotFound:
        _conf = read_configuration(
            path.join(
                path.dirname(path.dirname(__file__)),
                'setup.cfg'
            )
        )
        return _conf['metadata']['version']


__version__ = _extract_version('pipenv')
```

Example of requirements management:
```
[options]
install_requires =
    curio
    requests

[options.extras_require]
dev =
    wheel
test =
    pytest
```
And you can use this like:
```
$ pip install curequests[dev]
$ pip install curequests[dev, test]
$ # simplify contributors for setup environment
```

**Comment by 4383** [comment]
Every components of your CI/CD workflow can get version number dynamicaly directly from your python code or from config, so per example you can interact directly with your package for obtain git tag number according to the semver and project lifecycle

**Comment by guyskk** [comment]
Thanks for your reply, this seems a good idea.
Can the `MANIFEST.in` and `tox.ini` be replaced by `setup.cfg`?

**Comment by 4383** [comment]
`tox.ini` seems to be not compatible for moment with setup.cfg.
Right now there's a lot of discussion and proposal to incorporate the tox config into setup.cfg but it's not implemented for the moment.

`MANIFEST.in` help you to integrate all non python file in your package, but it seems to be complementary with `setup.cfg`.

Instead of using MANIFEST.in for every files you can use this code in your `setup.cfg`:
```
[options.package_data]
* = *.txt, *.rst
hello = *.msg
```
But becareful to do not use `[options.package_data]` with the `include_package_data = True` option.

Anyway a lot of python package (flake8, pytest, etc...) are ready to use `setup.cfg` so you can gohead!

**Comment by 4383** [comment]
You can use a lot of python modules for helping you to manage your project lifecycle:
- check-manifest `pip install check-manifest` (check file inclusions)
- prospector `pip install prospector` (code inspection (pylint, pep8, etc...))
- pyroma `pip install pyroma` (check setup.cfg values)
- zest.releaser `pip install zest.releaser` (bump version, changelog, etc...)
- readme-renderer `pip install readme-renderer` (generate html from long_description)
- etc...

**Comment by guyskk** [comment]
I agree with the point of https://github.com/pypa/sampleproject/pull/57
> It's a bit too early to move to setup.cfg based metadata.

**Comment by 4383** [comment]
Ok, I understand.
sampleproject is project skeleton used with various version of python 2.6, 2.7, 3.2, 3.3, etc....
In your case your already have prerequisite on python 3.6 so you already use an up-to-date version of python, I think this modification fit well with your project dependencies and environment.

I leave this pull request open so you can integrate it when you think it's the right time :)

You are welcome!

**Comment by 4383** [comment]
This changes can help users to have more confidence to your package.
Currently on private companies projects, they realize static analyzes of dependencies or inspect code before using it in their projects to make sure it's not a malicious dependencies.

A good example of this fact is the typo squatting. 
[Here you can see](https://github.com/pypa/pypi-legacy/issues/644) how works malicious projects.

**Comment by 4383** [comment]
@guyskk only you and your contributors are constrain setuptools on specific version.
In my previous changes I have make a mistake, I have specify in `README.md` in the `how to install` and in `prerequisites` to update setuptools in recent version, this is a mistake...

### Explanation
You already have build your package and push it to pypi so any version of `setuptools` through `pip` usage will do the trick.

Only you and others contributors must use an version of `setuptools` greater than `30.3.0`. :)

### Conclusion
[Pypa sampleproject](https://github.com/pypa/sampleproject) was a bad example in your case, this a skeleton project for development, and and their users and their development machines can be not up-to-date and can fail on build steps, the fault of setuptools... but your final users do not have to keep in mind to update their environments.

**Pull request closed without merging**
